apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: agentops-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: agentops-api-config
    patch: |-
      - op: replace
        path: /data/AGENTOPS_ENV
        value: prod
      - op: replace
        path: /data/AGENTOPS_RATE_LIMIT_PER_MIN
        value: "30"
images:
  - name: agentops-api
    newName: agentops-api
    newTag: local
